name: Build
on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        version: ["PHP-8.3", "PHP-8.4", "master"]

    runs-on: ubuntu-latest

    steps:
      - name: Setup Ubuntu
        run: sudo apt-get update && sudo apt-get install -y lcov re2c bison libargon2-dev libhiredis-dev

      - name: Install PHP
        run: |
          sudo mkdir /opt/src
          sudo chmod 777 /opt/src
          cd /opt/src
          git clone --depth=1 --branch ${{matrix.version}} https://github.com/php/php-src
          cd php-src
          ./buildconf --force
          ./configure --disable-all \
            --enable-gcov \
            --enable-opcache \
            --disable-opcache-jit \
            --prefix=/opt \
            --with-config-file-path=/opt/etc
          make -j$(nproc)
          sudo make install

      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate Build Files
        run: /opt/bin/phpize

      - name: Configure Build
        run: ./configure --enable-necrofile --with-php-config=/opt/bin/php-config

      - name: Build
        run: make
